### ISSUE TITLE
Installation Instructions Don't Work for Windows

### ISSUE THREAD

**Issue by DarioS** [NKI-CCB/DISCOVER#1]
The instructions need to be improved for installing in Windows.

    > options(repos=c(getOption("repos"), "http://ccb.nki.nl/software/discover/repos/r"))
    > install.packages("discover")
    Installing package into ‘C:/Users/Dario/Documents/R/win-library/3.3’
    (as ‘lib’ is unspecified)
    --- Please select a CRAN mirror for use in this session ---
      also installing the dependency ‘matrixStats’
    
    Package which is only available in source form, and may need compilation of C/C++/Fortran:
      ‘discover’
    These will not be installed

Instead of hosting on GitHub, it would be better if the software had adequate documentation (`Rd` files in a `man` folder) to be accepted into CRAN or Bioconductor.

**Comment by scanisius** [comment]
Thanks for reporting this issue. Are you by any chance running a 32-bit version of R?

**Comment by DarioS** [comment]
Yes, I am using a 32-bit R and a 32-bit operating system.

**Comment by scanisius** [comment]
The Windows package had been built for 64-bit R only. I now uploaded new Windows packages that are compatible with both 32-bit and 64-bit R. I think this will fix the problem you ran into.

As for your suggestion to make DISCOVER available on CRAN: I will indeed submit to CRAN soon. In the meantime, please note that there already is documentation for the most important functions in the current package. See `help(package=discover)` and the package vignette.
