### ISSUE TITLE
Important Documentation Missing

### ISSUE THREAD

**Issue by DarioS** [NKI-CCB/DISCOVER#10]
The software is described as

> DISCOVER is a novel statistical test for detecting **co-occurrence** and mutual exclusivity in cancer genomics data.

but the vignette doesn't have any example of how to test for co-occurrence

> We can now test for mutual exclusivity between all pairs of genes ...

Can DISCOVER R package do a test for co-occurrence?

Also, the functions lack any documentation.

> No man pages found in package  ‘discover’

Lastly, I think it would also be beneficial to many readers to have an example of converting a MAF file obtained from Genomic Data Commons into the matrix used rather than just `data("BRCA.mut")`.

**Comment by scanisius** [comment]
Thank you for reporting this issue. Unfortunately, the function-level documentation has not been included in the DISCOVER distribution packages, even though it is present in the R source files. I will fix this and also extend the vignette.

In the meantime, let me explain to you how to use the co-occurrence test. The `pairwise.discover.test` takes an optional argument called `alternative`. If its value is `"less"` (the default), a mutual exclusivity test is performed. If its value is `"greater"`, a co-occurrence test is performed.

**Comment by scanisius** [comment]
The latest version of the DISCOVER R package (0.9.3) now includes function-level help pages. These can be accessed using R's standard `?` syntax, e.g. `?pairwise.discover.test`.
