### ISSUE TITLE
Installation Fails on Debian 10

### ISSUE THREAD

**Issue by DarioS** [NKI-CCB/DISCOVER#11]
The software installation worked on Debian 9 last year. The system administrator upgraded the server to Debian 10 during holidays. Now, I can't install DISCOVER.

```
logspace.f90:12:22:

     real(dp), volatile :: z
                      1
Error: VOLATILE attribute at (1) cannot be specified in a PURE procedure
logspace.f90:14:5:

     z = 1.0d0 + x
     1
Error: Symbol ‘z’ at (1) has no IMPLICIT type
make: *** [/usr/lib/R/etc/Makeconf:195: logspace.o] Error 1
ERROR: compilation failed for package ‘discover’
* removing ‘/dskh/nobackup/biostat/Bioconductor/discover
```

Can the Fortran code be updated for newer compilers (Fortran is now at version 8.3)? It seems this problem was fixed before #9 but it happens to me today. Perhaps the fix needs to be made to the repository http://ccb.nki.nl/software/discover/repos/r which the installation instructions advise the end-user to set.

**Comment by scanisius** [comment]
This problem has indeed been fixed in the git repository. Unfortunately, we cannot currently upload new packages to our package repository. We are working to resolve this as soon as possible.

In the meantime, you can install the latest version using the `install_github` function from the [`remotes`](https://cran.r-project.org/web/packages/remotes/) package.

```R
library(remotes)
install_github("NKI-CCB/DISCOVER", subdir="R")
```

**Comment by scanisius** [comment]
The latest version of the DISCOVER R package (0.9.3) has now been uploaded to our package repository. So you should be able to follow the original installation instructions again and no longer encounter the compilation error.

**Comment by DarioS** [comment]
Installation has worked on Debian 10.
