### ISSUE TITLE
Hi. I cannot install the package 'discover'.

### ISSUE THREAD

**Issue by jdjdj0202** [NKI-CCB/DISCOVER#12]
Hi. I cannot install the package 'discover'.

options(repos=c(getOption("repos"), "http://ccb.nki.nl/software/discover/repos/r"))
install.packages("discover")

The codes lead to errors.

Warning in install.packages :
  unable to access index for repository http://ccb.nki.nl/software/discover/repos/r/bin/windows/contrib/4.0:
  URL 'http://ccb.nki.nl/software/discover/repos/r/bin/windows/contrib/4.0/PACKAGES' cannot be opened. 
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘discover’
  These will not be installed.

I am a beginner, so I'd really appreciate it if you could give me advice. 
Thanks.

**Comment by scanisius** [comment]
Thanks for reporting this. You saw this error because the DISCOVER package was not available yet for R 4.0. I now uploaded the new version. If you repeat the installation commands it should work.
