### ISSUE TITLE
Stratifying data

### ISSUE THREAD

**Issue by FireHavvk** [NKI-CCB/DISCOVER#16]
Hi, 
I'm working on a study on genetic interactions within different types of paediatric acute leukaemia. I want to add different tumour types together, but have been unable to stratify the data per tumour type and than add together all the data into one big matrix. How did you go about stratifying the pan cancer data described in your paper?

Kind regards,
Charlotte

**Comment by scanisius** [comment]
The option to stratify your analysis is available as an extra argument to the `discover.matrix` (in R) or `DiscoverMatrix` (in Python) function. This argument is called `strata`. To stratify, you pass a vector of length equal to the number of tumours in your mutation matrix where the values specify the stratum (in your case the tumour type) for the corresponding tumours.

The following R example code illustrates this using the `BRCA.mut` data included in the discover package.
```R
subtypes <- sample(c("TYPE1", "TYPE2"), ncol(BRCA.mut), replace=TRUE)   # replace this by the actual tumour types
events <- discover.matrix(BRCA.mut, strata=subtypes)
```

**Comment by scanisius** [comment]
This issue has been inactive for a while now, so I am closing it. Please open a new issue if you are still experiencing problems with DISCOVER.
