### ISSUE TITLE
how to create the input file?

### ISSUE THREAD

**Issue by stroke1989** [NKI-CCB/DISCOVER#18]
Hi,
Thanks for this awesome tool, I tried to use DISCOVER  to analyze my data, but I'm not a bioinformatist, I don't know how to create the input file， a matrix  as below:
<img width="471" alt="Snipaste_2022-07-28_21-17-12" src="https://user-images.githubusercontent.com/61864553/181515124-c0f6cec9-39db-4456-a331-7a4a3fb87b05.png">

Hope your response! Appreciate!

**Comment by scanisius** [comment]
The mutation matrix that you need for DISCOVER has genes in the rows and tumours in the columns. The values in that matrix are either 0 or 1, where 1 indicates a mutation in the particular gene and tumour, and 0 indicates the absence of such a mutation.

The steps you need to take to create the input matrix for DISCOVER will depend on the type of data you start with, so I can't comment on your particular situation. Have a look at the description in #7 for an example of how to create a mutation matrix from TCGA mutation data. This description expects the mutation data to be available in MAF format. If your data are stored in VCF format instead, you might use a tool like [vcf2maf](https://github.com/mskcc/vcf2maf) to create a MAF file.

**Comment by scanisius** [comment]
This issue has been inactive for a while now, so I am closing it. Please open a new issue if you are still experiencing problems with DISCOVER.
