### ISSUE TITLE
multi-omics analysis and FDR filtering

### ISSUE THREAD

**Issue by Tesson98** [NKI-CCB/DISCOVER#19]
Dear @mschubert ，
       &ensp; &ensp; Thanks for releasing this powerful tool.
       &ensp; &ensp; Recent I have read a paper using "DISCOVER" in the exclusivity analysis between virus infection and gene mutations (Zapatka M, Borozan I, Brewer DS, et al. The landscape of viral associations in human cancers. Nat Genet. 2020;52(3):320-330. doi:10.1038/s41588-019-0558-9), which raising my interest in the relationship between gene fusions and gene mutations.
       &ensp; &ensp; But there are still some questions which I hope to get some suggestions from you.
       &ensp; &ensp; First, I know "DISCOVER" was developed for the whole-genome wide mutation analysis. So in your view, is it suitable for the analysis in the whole-genome wide "gene-fusion" analysis? (I have more than 5000 gene-fusions in one single tumor type)
       &ensp; &ensp; Second, if "DISCOVER" is suitable for  "gene-fusion" analysis, can I implement  this method in the combination data of gene fusions and gene mutations (I only have data of 55 gene mutations, but it's noted that "Even if only a subset of genes will subsequently be used in the analysis, a **whole-genome view of the mutations** is required for this first step" in the method's R introduction ) ? Can I use this method in the exclusivity analysis among gene-fusions, among gene mutation, and between the gene fusions and mutations?Should I create a matrix with rows correspond to fusions and mutations, and columns to samples **(example as below)**?
        &ensp; &ensp; Finally, it's noted that "To get the pairs of genes which are significantly mutually exclusive, we can use the as.data.frame method. This method, too, **takes an optional FDR threshold as argument.** " in the method's R introduction, but when I use as.data.frame(results_myfusionandgene_ex), I can't find the argument for FDR threshold chosing, could you help me with this problem?
        &ensp; &ensp; Thanks again and really look forward to your reply.
&ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp;  Tesson,Dec 6th, 2022

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TIANSH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TIANSH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | fusion1 | fusion2 | fusion3 | … | fusion5000 | mutation1 | mutation2 | … | mutation55
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
sample1 | 1 | 1 | 0 | … |   | 1 | 0 | 1 | 0
sample2 | 1 | 1 | 0 | … |   | 1 | 0 | 0 | 1
sample3 | 1 | 0 | 1 | … |   | 1 | 0 | 0 | 0
sample4 | 1 | 0 | 1 | … |   | 0 | 0 | 1 | 1
sample5 | 0 | 0 | 0 | … | 1 | 0 | 0 | 1 | 0
… | … | … | … | … | … | … | … | … | …
sample200 | 0 | 0 | 1 | … | 1 | 0 | 0 | 1 | 0

</body>

</html>

**Comment by mschubert** [comment]
Pinging @scanisius because this is his tool and not mine
