### ISSUE TITLE
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found 

### ISSUE THREAD

**Issue by srinipr4** [NKI-CCB/DISCOVER#5]
Hi, I am able to install discover using anaconda without any issues. However, when I try to import the library inside python, I get this error:
>>> import discover
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/username/anaconda2/lib/python2.7/site-packages/_discover.so)

**Comment by scanisius** [comment]
The problem seems to be that your system's C library is older than the version that is expected by the DISCOVER package. Are you able to update the glibc (or libc6) package on your system?

**Comment by scanisius** [comment]
This issue has been inactive for a few months, so I am closing it. I hope my response helped you solve the problem. Please open a new issue if you continue to encounter this error.
